### ISSUE TITLE
大佬，我的音乐播放不了，榜单也出不来

### ISSUE THREAD

**Issue by bywtmzm** [zyb718116577/wxmusic#10]
显示：VM10568 asdebug.js:1 GET https://c.y.qq.com/musichall/fcgi-bin/fcg_yqqhomepagerecommend.fcg?g_tk=5381&inCharset=utf-8&outCharset=utf-8&notice=0&format=jsonp&platform=h5&uin=0&needNewCode=1&jsonpCallback=callback 500 (Internal Server Error)

**Comment by zyb718116577** [comment]
重新更新一下代码试试，今天提了最新版




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"bywtmzm"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月24日(星期五) 下午4:28
收件人:&nbsp;"zyb718116577/wxmusic"<wxmusic@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[zyb718116577/wxmusic] 大佬，我的音乐播放不了，榜单也出不来 (#10)





 
显示：VM10568 asdebug.js:1 GET https://c.y.qq.com/musichall/fcgi-bin/fcg_yqqhomepagerecommend.fcg?g_tk=5381&amp;inCharset=utf-8&amp;outCharset=utf-8&amp;notice=0&amp;format=jsonp&amp;platform=h5&amp;uin=0&amp;needNewCode=1&amp;jsonpCallback=callback 500 (Internal Server Error)

**Comment by bywtmzm** [comment]
> 重新更新一下代码试试，今天提了最新版
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"bywtmzm"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月24日(星期五) 下午4:28 收件人:&nbsp;"zyb718116577/wxmusic"<wxmusic@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[zyb718116577/wxmusic] 大佬，我的音乐播放不了，榜单也出不来 (#10) 显示：VM10568 asdebug.js:1 GET https://c.y.qq.com/musichall/fcgi-bin/fcg_yqqhomepagerecommend.fcg?g_tk=5381&amp;inCharset=utf-8&amp;outCharset=utf-8&amp;notice=0&amp;format=jsonp&amp;platform=h5&amp;uin=0&amp;needNewCode=1&amp;jsonpCallback=callback 500 (Internal Server Error) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，谢谢
